const avatars=['😀','😎','🤠','🤖','👽','🐸','🦊','🐼','🐵','🐙','🦄','👻','🐯','🧠','👾'];
const storage={get:(k,d='')=>{try{return localStorage.getItem(k)||d}catch{return d}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch{}}};
const state={screen:'home',name:storage.get('collageName',''),avatar:storage.get('collageAvatar','😀'),ws:null,pid:null,code:'',game:null,error:'',settings:{capacity:8,imagesPerPlayer:2,round1Images:4,hostApproval:false,creationSeconds:120,votingSeconds:45},lobby:'My Collage',prompt:'',sources:[],sourceSelected:null,pieces:[],selected:null,cutting:false,cutPath:[],sourceWorking:{},drag:null};
const app=document.querySelector('#app');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function send(action){if(state.ws?.readyState===1)state.ws.send(JSON.stringify({type:'ACTION',playerId:state.pid,action}));}
function connect(first){const proto=location.protocol==='https:'?'wss':'ws';state.ws=new WebSocket(`${proto}://${location.host}/ws`);state.ws.onopen=()=>first(state.ws);state.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='JOINED'){state.pid=m.playerId;state.code=m.code;state.screen='game';render()}else if(m.type==='STATE'){state.game=m.state;if(state.game.phase!=='ROUND'){state.pieces=[];state.selected=null;state.sourceSelected=null;state.cutting=false;state.cutPath=[];state.sourceWorking={}}render()}else if(m.type==='ERROR'){state.error=m.message;render()}};state.ws.onclose=()=>{state.error='Disconnected from the game server.';render()}}
function home(){return `<div class="shell"><div class="hero"><div class="brand">SHUFFLE • COLLAGE</div><h1>COLLAGE</h1><div class="tag">Cut it. Build it. Shuffle it. 😈</div><div class="menu"><button onclick="go('host')">🎮 Host Game</button><button onclick="go('join')">🚪 Join Game</button></div></div><div class="profile"><h3>👤 Your profile</h3><input value="${esc(state.name)}" oninput="setName(this.value)" placeholder="Nickname"><div class="avatars">${avatars.map(a=>`<button class="${a===state.avatar?'selected':''}" onclick="setAvatar('${a}')">${a}</button>`).join('')}</div></div><p class="roundNote">V1.2.0 • Shuffle mode</p></div>`}
function host(){return `<div class="shell"><div class="brand">HOST GAME</div><h2>Set up your chaos</h2><div class="form"><input value="${esc(state.lobby)}" oninput="state.lobby=this.value" placeholder="Lobby name"></div><div class="settings">${setting('Player capacity','capacity',2,16)}${setting('Images per player','imagesPerPlayer',1,10)}${setting('Round 1 images','round1Images',1,12)}${setting('Creation time (sec)','creationSeconds',30,600)}${setting('Voting time (sec)','votingSeconds',15,300)}<div class="setting"><small>Host image approval</small><label><input type="checkbox" ${state.settings.hostApproval?'checked':''} onchange="state.settings.hostApproval=this.checked"> Review submitted images before the game starts</label></div></div><div class="row" style="margin-top:18px"><button onclick="startHost()">Create Lobby →</button><button class="secondary" onclick="go('home')">Back</button></div>${state.error?`<p class="error">${esc(state.error)}</p>`:''}</div>`}
function setting(label,key,min,max){return `<div class="setting"><small>${label}</small><input type="number" min="${min}" max="${max}" value="${state.settings[key]}" onchange="state.settings[key]=+this.value"></div>`}
function join(){return `<div class="shell"><div class="brand">JOIN GAME</div><h2>Jump into a lobby</h2><div class="form"><label><b>Nickname</b></label><input value="${esc(state.name)}" oninput="setName(this.value)" placeholder="What should everyone call you?" maxlength="24"><label><b>Lobby code</b></label><input value="${esc(state.code)}" oninput="state.code=this.value.toUpperCase()" placeholder="4-letter lobby code" maxlength="4"><button onclick="startJoin()">Join Lobby →</button></div>${state.error?`<p class="error">${esc(state.error)}</p>`:''}<button class="secondary" onclick="go('home')">Back</button></div>`}
function lobby(){const g=state.game,me=g.players.find(p=>p.id===state.pid);return `<div class="shell"><div class="brand">LOBBY</div><h2>${esc(g.name)}</h2><div class="code">${state.code}</div><p style="text-align:center">Send this code to your friends. Everyone can join from their own PC.</p><div class="players">${g.players.map(p=>`<div class="player">${p.avatar} <b>${esc(p.name)}</b>${p.host?' 👑':''}<span class="status">${p.connected?(p.host?'Host':p.ready?'Ready':'Not ready'):'✕ Offline'}</span></div>`).join('')}</div><div class="row" style="margin-top:18px">${me.host?`<button ${g.players.length<2?'disabled':''} onclick="send({type:'START'})">Start Game 🚀</button>`:`<button onclick="send({type:'SET_READY',ready:${!me.ready}})">${me.ready?'✓ Ready — click to undo':'Ready up'}</button>`}<span class="notice">${g.players.length}/ ${g.settings.capacity} players • testing minimum 2</span></div></div>`}
function imageSubmit(){const mine=state.game.sources.filter(s=>s.ownerId===state.pid);const need=state.game.settings.imagesPerPlayer;return `<div class="shell"><div class="brand">ROUND SETUP</div><h2>📸 Build the image pool</h2><p>Submit <b>${need}</b> image${need===1?'':'s'}. Upload, drag-and-drop, or copy an image and press <b>Ctrl+V</b>.</p><div id="drop" class="drop" tabindex="0" ondragover="event.preventDefault();this.classList.add('drag')" ondragleave="this.classList.remove('drag')" ondrop="handleDrop(event)"><strong>Drop images here</strong><br><button type="button" class="secondary" onclick="event.stopPropagation();document.querySelector('#file').click()">Choose image files</button><br><small>Or copy an image and press Ctrl+V</small><input id="file" class="hidden" type="file" accept="image/*" multiple onchange="files(this.files);this.value=''" ></div><div class="thumbs">${mine.map(s=>`<div class="thumb"><img src="${s.data}"></div>`).join('')}</div><div class="row" style="margin-top:18px"><span class="notice">${mine.length}/${need} uploaded</span>${mine.length>=need?'<span class="notice">✓ Submitted — waiting for everyone</span>':'<span>Keep adding images…</span>'}</div></div>`}
function approval(){return `<div class="shell"><div class="brand">HOST CHECK</div><h2>🕵️ Approve the image pool</h2><div class="thumbs">${state.game.sources.map(s=>`<div class="thumb"><img src="${s.data}"><button onclick="send({type:'DELETE_SOURCE',sourceId:'${s.id}'})">Delete</button></div>`).join('')}</div>${state.game.players.find(p=>p.id===state.pid)?.host?'<button style="margin-top:18px" onclick="send({type:\'APPROVAL_DONE\'})">Looks good — continue →</button>':'<p class="notice">Waiting for the host…</p>'}</div>`}
function prompts(){const count=state.game.prompts.length,total=state.game.players.length;return `<div class="shell"><div class="brand">PROMPT ROUND</div><h2>✍️ Give everyone something ridiculous to make</h2><textarea id="prompt" oninput="state.prompt=this.value" style="width:100%;min-height:130px;padding:15px;border:3px solid var(--ink);border-radius:16px" placeholder="Write a sentence, scenario or idea…">${esc(state.prompt)}</textarea><div class="row" style="margin-top:14px"><button onclick="submitPrompt()">Submit Prompt →</button><span class="notice">${count}/${total} submitted</span></div></div>`}
function round(){
  const g=state.game,prompt=g.prompts.find(p=>p.id===g.currentPromptId)?.text||'';
  const remaining=Math.max(0,Math.ceil((g.timerEndsAt-Date.now())/1000));
  if(!state.pieces.length&&g.round>0){
    const owner=g.roundPlayerSets[state.pid];
    const source=Object.values(g.collages||{}).find(c=>c.playerId===owner);
    if(source)state.pieces=scatter(source.pieces);
  }
  const selectedSrc=g.sources.find(s=>s.id===state.sourceSelected);
  return `<div class="shell wide"><div class="promptBanner"><div><small>ROUND ${g.round+1} OF ${g.players.length}</small><h2>${esc(prompt)}</h2></div><div class="timer">⏱ ${remaining}s</div></div><div class="editorGrid"><aside><div class="sourcePanel">${g.round===0?`<h3>🖼 Your ingredients</h3><p>Choose an image, press <b>Cut</b>, then draw a freehand shape around exactly what you want.</p><div class="sourceList">${g.sources.map(s=>`<button class="sourceBtn ${state.sourceSelected===s.id?'active':''}" onclick="selectSource('${s.id}')"><img src="${state.sourceWorking[s.id]||s.data}"></button>`).join('')}</div>${selectedSrc?`<div class="cutBox"><div class="cutHead"><b>${state.cutting?'✂ Draw your cut shape':'Selected image'}</b>${state.cutting?'<span>Draw a closed shape around the piece</span>':''}</div><div class="cutStage" id="cutStage" onpointerdown="cutDown(event)" onpointermove="cutMove(event)" onpointerup="cutUp(event)" onpointercancel="cutCancel(event)"><img id="cutImage" draggable="false" src="${state.sourceWorking[state.sourceSelected]||selectedSrc.data}">${state.cutting&&state.cutPath.length>1?`<svg class="cutOverlay" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="${state.cutPath.map(pt=>`${pt.x},${pt.y}`).join(' ')}" /></svg>`:''}</div><button ${state.cutting?'disabled':''} onclick="startCut()">✂ ${state.cutting?'Drawing…':'Cut a piece'}</button></div>`:''}`:`<h3>🔀 Shuffled pieces</h3><p>These pieces came from another player's collage. Rearrange them.</p>`}</div><div class="toolPanel" style="margin-top:12px"><div class="toolbar"><button onclick="rotate(-15)">↺</button><button onclick="rotate(15)">↻</button><button onclick="flip('x')">↔</button><button onclick="flip('y')">↕</button><button onclick="layer(-1)">↓</button><button onclick="layer(1)">↑</button></div><button style="width:100%;background:var(--green)" onclick="submitCollage()">Submit collage ✓</button></div></aside><div class="canvas" id="canvas" onpointerdown="canvasDown(event)">${state.pieces.map(p=>`<img class="piece ${state.selected===p.id?'selected':''}" draggable="false" src="${p.src}" style="left:${p.x}%;top:${p.y}%;width:${p.w||24}%;transform:translate(-50%,-50%) rotate(${p.rotation||0}deg) scaleX(${p.flipX?-1:1}) scaleY(${p.flipY?-1:1});z-index:${p.z||0}" onpointerdown="pieceDown(event,'${p.id}')">`).join('')}</div></div><p class="roundNote">${g.round===0?'Round 1: freehand-cut pieces from your source images.':'No cutting this round — only rearrange what you inherited.'} • Pieces: ${state.pieces.length}</p></div>`
}
function voting(){const g=state.game;const remaining=Math.max(0,Math.ceil((g.timerEndsAt-Date.now())/1000));setTimeout(()=>{if(state.game?.phase==='VOTING')render()},500);return `<div class="shell wide"><div class="promptBanner"><div><small>VOTE</small><h2>${esc(g.prompts.find(p=>p.id===g.currentPromptId)?.text||'')}</h2></div><div class="timer">⏱ ${remaining}s</div></div><p>Pick the collage that best answers the prompt. <b>No names are shown.</b></p><div class="voteGrid">${Object.values(g.collages).map(c=>`<div class="voteCard">${canvasHTML(c.pieces)}${c.playerId===state.pid?'<div class="notice" style="margin-top:8px">Your collage</div>':`<button style="width:100%;margin-top:8px" onclick="send({type:'VOTE',targetId:'${c.playerId}'})">Vote for this</button>`}</div>`).join('')}</div></div>`}
function canvasHTML(ps){return `<div class="miniCanvas">${ps.map(p=>`<img src="${p.src}" style="left:${p.x}%;top:${p.y}%;width:${p.w||24}%;transform:translate(-50%,-50%) rotate(${p.rotation||0}deg) scaleX(${p.flipX?-1:1}) scaleY(${p.flipY?-1:1})">`).join('')}</div>`}
function reveal(){const g=state.game;return `<div class="shell wide"><div class="brand">RESULTS</div><h2>🎉 Round ${g.round+1} results</h2><div class="voteGrid">${Object.values(g.collages).sort((a,b)=>(g.lastTally?.[b.playerId]||0)-(g.lastTally?.[a.playerId]||0)).map(c=>`<div class="voteCard">${canvasHTML(c.pieces)}<div class="result"><span>${g.lastTally?.[c.playerId]||0} votes</span></div></div>`).join('')}</div>${state.game.players.find(p=>p.id===state.pid)?.host?'<button style="margin-top:18px" onclick="send({type:\'NEXT\'})">Next round →</button>':'<p class="notice">Waiting for the host to continue…</p>'}</div>`}
function final(){const rows=[...state.game.players].sort((a,b)=>(state.game.scores[b.id]||0)-(state.game.scores[a.id]||0));return `<div class="shell"><div class="brand">FINAL SHOWCASE</div><h1>🏆</h1><h2>The Collage Hall of Shame</h2>${rows.map((p,i)=>`<div class="result"><b>${i+1}. ${esc(p.name)}</b><span>${state.game.scores[p.id]||0} pts</span></div>`).join('')}<p class="roundNote">Thanks for playing Shuffle.</p></div>`}
function updateTimerOnly(){const el=document.querySelector('.timer'); if(el && state.game?.timerEndsAt){el.textContent='⏱ '+Math.max(0,Math.ceil((state.game.timerEndsAt-Date.now())/1000))+'s';}}
setInterval(updateTimerOnly,250);
function render(){
  const focusedPrompt=document.activeElement?.id==='prompt';
  const promptValue=focusedPrompt?document.activeElement.value:state.prompt;
  let html=state.screen==='home'?home():state.screen==='host'?host():state.screen==='join'?join():state.game?.phase==='LOBBY'?lobby():state.game?.phase==='IMAGE_SUBMISSION'?imageSubmit():state.game?.phase==='HOST_APPROVAL'?approval():state.game?.phase==='PROMPT_SUBMISSION'?prompts():state.game?.phase==='ROUND'?round():state.game?.phase==='VOTING'?voting():state.game?.phase==='REVEAL'?reveal():state.game?.phase==='FINAL'?final():`<div class="shell">Connecting…</div>`;
  app.innerHTML=html;
  if(focusedPrompt){const el=document.querySelector('#prompt');if(el){el.value=promptValue;el.focus();el.setSelectionRange(el.value.length,el.value.length)}}
  if(state.game?.phase==='IMAGE_SUBMISSION'){document.onpaste=e=>{const items=[...(e.clipboardData?.items||[])];for(const item of items)if(item.type.startsWith('image/')){const f=item.getAsFile();if(f)files([f])}}}else document.onpaste=null;
}
function go(s){state.screen=s;state.error='';render()}
function setName(v){state.name=v;storage.set('collageName',v)}
function setAvatar(v){state.avatar=v;storage.set('collageAvatar',v);render()}
function startHost(){if(!state.name.trim()){state.error='Choose a nickname first.';render();return}connect(ws=>ws.send(JSON.stringify({type:'HOST_CREATE',name:state.name,avatar:state.avatar,lobbyName:state.lobby,settings:state.settings})))}
function startJoin(){if(!state.name.trim()){state.error='Choose a nickname first.';render();return}connect(ws=>ws.send(JSON.stringify({type:'JOIN',name:state.name,avatar:state.avatar,code:state.code})))}
function files(list){const existing=state.game.sources.filter(s=>s.ownerId===state.pid).length;[...list].slice(0,10-existing).forEach(file=>{if(state.game.sources.filter(s=>s.ownerId===state.pid).length>=state.game.settings.imagesPerPlayer)return;const r=new FileReader();r.onload=()=>send({type:'ADD_SOURCE',data:r.result});r.readAsDataURL(file)})}
function handleDrop(e){e.preventDefault();e.currentTarget.classList.remove('drag');files(e.dataTransfer.files)}
function submitPrompt(){const t=document.querySelector('#prompt')?.value.trim();if(t){state.prompt=t;send({type:'ADD_PROMPT',text:t})}}
function selectSource(id){state.sourceSelected=id;state.cutting=false;state.cutPath=[];render()}
function startCut(){if(!state.sourceSelected){alert('Pick an image first.');return}state.cutting=true;state.cutPath=[];render()}
function cutPoint(e){const stage=e.currentTarget,r=stage.getBoundingClientRect();return {x:Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))}}
function updateCutPath(){const poly=document.querySelector('.cutOverlay polyline');if(poly)poly.setAttribute('points',state.cutPath.map(pt=>`${pt.x},${pt.y}`).join(' '))}
function cutDown(e){if(!state.cutting)return;state.cutPath=[cutPoint(e)];e.currentTarget.setPointerCapture?.(e.pointerId);updateCutPath()}
function cutMove(e){if(!state.cutting||!state.cutPath.length)return;const pt=cutPoint(e),last=state.cutPath[state.cutPath.length-1];if(Math.hypot(pt.x-last.x,pt.y-last.y)>0.7){state.cutPath.push(pt);updateCutPath()}}
function cutUp(){if(!state.cutting||state.cutPath.length<3){cutCancel();return}cropSelected()}
function cutCancel(){state.cutPath=[];state.cutting=false;render()}
function cropSelected(){
  const src=state.game.sources.find(s=>s.id===state.sourceSelected),img=document.querySelector('#cutImage'),stage=document.querySelector('#cutStage');
  if(!src||!img||!stage||state.cutPath.length<3)return;
  const sr=stage.getBoundingClientRect(),ir=img.getBoundingClientRect();
  const pts=state.cutPath.map(pt=>({x:(pt.x/100*sr.width-(ir.left-sr.left))*img.naturalWidth/ir.width,y:(pt.y/100*sr.height-(ir.top-sr.top))*img.naturalHeight/ir.height})).map(pt=>({x:Math.max(0,Math.min(img.naturalWidth,pt.x)),y:Math.max(0,Math.min(img.naturalHeight,pt.y))}));
  const minX=Math.floor(Math.min(...pts.map(p=>p.x))),maxX=Math.ceil(Math.max(...pts.map(p=>p.x))),minY=Math.floor(Math.min(...pts.map(p=>p.y))),maxY=Math.ceil(Math.max(...pts.map(p=>p.y)));
  const bw=Math.max(1,maxX-minX),bh=Math.max(1,maxY-minY),scale=Math.min(1,700/Math.max(bw,bh));
  const outW=Math.max(2,Math.round(bw*scale)),outH=Math.max(2,Math.round(bh*scale));
  const canvas=document.createElement('canvas');canvas.width=outW;canvas.height=outH;const ctx=canvas.getContext('2d');
  ctx.clearRect(0,0,outW,outH);ctx.save();ctx.beginPath();pts.forEach((p,i)=>{const x=(p.x-minX)*scale,y=(p.y-minY)*scale;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.clip();ctx.drawImage(img,minX,minY,bw,bh,0,0,outW,outH);ctx.restore();
  const piece={id:crypto.randomUUID(),src:canvas.toDataURL('image/png'),x:50,y:50,w:30,rotation:0,flipX:false,flipY:false,z:state.pieces.length};state.pieces.push(piece);state.selected=piece.id;
  const workCanvas=document.createElement('canvas');workCanvas.width=img.naturalWidth;workCanvas.height=img.naturalHeight;const wctx=workCanvas.getContext('2d');wctx.drawImage(img,0,0);wctx.save();wctx.globalCompositeOperation='destination-out';wctx.beginPath();pts.forEach((p,i)=>{i?wctx.lineTo(p.x,p.y):wctx.moveTo(p.x,p.y)});wctx.closePath();wctx.fill();wctx.restore();
  state.sourceWorking[state.sourceSelected]=workCanvas.toDataURL('image/png');state.cutting=false;state.cutPath=[];render()
}
function canvasDown(e){if(state.cutting)return}
function pieceDown(e,id){e.stopPropagation();state.selected=id;const p=state.pieces.find(x=>x.id===id);if(!p)return;const canvas=e.currentTarget.parentElement,r=canvas.getBoundingClientRect();state.drag={id,ox:e.clientX,oy:e.clientY,startX:p.x,startY:p.y,w:r.width,h:r.height,el:e.currentTarget};e.currentTarget.setPointerCapture?.(e.pointerId);e.currentTarget.onpointermove=ev=>{const dx=(ev.clientX-state.drag.ox)/state.drag.w*100,dy=(ev.clientY-state.drag.oy)/state.drag.h*100;p.x=Math.max(0,Math.min(100,state.drag.startX+dx));p.y=Math.max(0,Math.min(100,state.drag.startY+dy));state.drag.el.style.left=p.x+'%';state.drag.el.style.top=p.y+'%'};e.currentTarget.onpointerup=()=>{state.drag=null;render()};e.currentTarget.onpointercancel=()=>{state.drag=null;render()};e.currentTarget.style.cursor='grabbing';}
function rotate(d){const p=state.pieces.find(x=>x.id===state.selected);if(p){p.rotation=(p.rotation||0)+d;updatePieceStyle(p)}}
function flip(axis){const p=state.pieces.find(x=>x.id===state.selected);if(p){p[axis==='x'?'flipX':'flipY']=!(p[axis==='x'?'flipX':'flipY']);updatePieceStyle(p)}}
function layer(d){const p=state.pieces.find(x=>x.id===state.selected);if(p){p.z=Math.max(0,(p.z||0)+d);render()}}
function updatePieceStyle(p){const el=document.querySelector(`.piece[src="${CSS.escape(p.src)}"]`);if(el)el.style.transform=`translate(-50%,-50%) rotate(${p.rotation||0}deg) scaleX(${p.flipX?-1:1}) scaleY(${p.flipY?-1:1})`;}
function submitCollage(){send({type:'SUBMIT_COLLAGE',pieces:state.pieces})}
window.addEventListener('error',e=>{state.error='The game UI hit an error: '+(e.message||'unknown error');if(app)app.innerHTML='<div class="shell"><div class="brand">COLLAGE ERROR</div><h2>Something went wrong</h2><p>'+esc(state.error)+'</p><button onclick="location.reload()">Reload game</button></div>';});
window.addEventListener('unhandledrejection',()=>{state.error='The game UI hit an error.';});
window.go=go;window.setName=setName;window.setAvatar=setAvatar;window.startHost=startHost;window.startJoin=startJoin;window.files=files;window.handleDrop=handleDrop;window.submitPrompt=submitPrompt;window.selectSource=selectSource;window.startCut=startCut;window.canvasDown=canvasDown;window.pieceDown=pieceDown;window.rotate=rotate;window.flip=flip;window.layer=layer;window.submitCollage=submitCollage;window.cutDown=cutDown;window.cutMove=cutMove;window.cutUp=cutUp;window.cutCancel=cutCancel;
render();
