const VERSION='1.3.2';
const avatars=['😀','😎','🤠','🤖','👽','🐸','🦊','🐼','🐵','🐙','🦄','👻','🐯','🧠','👾'];
const state={screen:'home',name:localStorage.getItem('collageName')||'',avatar:localStorage.getItem('collageAvatar')||'😀',ws:null,pid:null,code:'',game:null,error:'',settings:{capacity:2,imagesPerPlayer:2,round1Images:4,hostApproval:false,creationSeconds:120,votingSeconds:45},lobby:'My Collage',prompt:'',sourceSelected:null,sourceWorking:{},pieces:[],selected:null,drag:null,timerHandle:null,cutCanvas:null,cutPoints:[],lastPhase:null};
const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID();
function send(action){if(state.ws?.readyState===1)state.ws.send(JSON.stringify({type:'ACTION',playerId:state.pid,action}));}
function connect(first){if(state.ws?.readyState===1)state.ws.close();const proto=location.protocol==='https:'?'wss':'ws';state.ws=new WebSocket(`${proto}://${location.host}/ws`);state.ws.onopen=()=>first(state.ws);state.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='JOINED'){state.pid=m.playerId;state.code=m.code;state.screen='game';state.error='';render(true)}else if(m.type==='STATE'){const old=state.game?.phase;state.game=m.state;if(state.game.phase!=='ROUND'){state.pieces=[];state.selected=null;state.drag=null}if(old!==state.game.phase)render(true);else updateLive();}else if(m.type==='ERROR'){state.error=m.message;render(true)}};state.ws.onclose=()=>{state.error='Disconnected from the game server.';render(true)}}
function home(){return `<div class="shell"><div class="hero"><div class="brand">SHUFFLE • COLLAGE</div><h1>COLLAGE</h1><div class="tag">Cut it. Build it. Shuffle it. 😈</div><div class="buildBadge">BUILD V${VERSION}</div><div class="menu"><button onclick="go('host')">🎮 Host Game</button><button onclick="go('join')">🚪 Join Game</button></div></div><div class="profile"><h3>👤 Your profile</h3><input value="${esc(state.name)}" oninput="setName(this.value)" placeholder="Nickname"><div class="avatars">${avatars.map(a=>`<button class="${a===state.avatar?'selected':''}" onclick="setAvatar('${a}')">${a}</button>`).join('')}</div></div><p class="roundNote">Shuffle testing build • 2-player minimum for testing</p></div>`}
function host(){return `<div class="shell"><div class="brand">HOST GAME</div><h2>Set up your chaos</h2><div class="form"><label><b>Lobby name</b></label><input value="${esc(state.lobby)}" oninput="state.lobby=this.value" placeholder="Lobby name"></div><div class="settings">${setting('Player capacity','capacity',2,16)}${setting('Images per player','imagesPerPlayer',1,10)}${setting('Round 1 images','round1Images',1,12)}${setting('Creation time (sec)','creationSeconds',30,600)}${setting('Voting time (sec)','votingSeconds',15,300)}<div class="setting"><small>Host image approval</small><label><input type="checkbox" ${state.settings.hostApproval?'checked':''} onchange="state.settings.hostApproval=this.checked"> Review submitted images before the game starts</label></div></div><div class="row" style="margin-top:18px"><button onclick="startHost()">Create Lobby →</button><button class="secondary" onclick="go('home')">Back</button></div>${state.error?`<p class="error">${esc(state.error)}</p>`:''}</div>`}
function setting(label,key,min,max){return `<div class="setting"><small>${label}</small><input type="number" min="${min}" max="${max}" value="${state.settings[key]}" onchange="state.settings[key]=+this.value"></div>`}
function join(){return `<div class="shell joinScreen"><div class="brand">JOIN GAME</div><h2>Join a Collage lobby</h2><div class="joinCallout">👋 <b>Joining for the first time?</b><br>Enter your nickname below — you do not need to go back to the profile screen.</div><div class="form joinForm"><label for="joinName"><b>👤 Your nickname</b></label><input id="joinName" autocomplete="nickname" value="${esc(state.name)}" oninput="setName(this.value)" placeholder="Type your nickname here" autofocus><label for="joinCode"><b>🔑 Lobby code</b></label><input id="joinCode" value="${esc(state.code)}" oninput="state.code=this.value.toUpperCase()" placeholder="4-letter lobby code" maxlength="4"><button onclick="startJoin()">Join Lobby →</button></div>${state.error?`<p class="error">${esc(state.error)}</p>`:''}<button class="secondary" onclick="go('home')">Back</button><p class="roundNote">Build V${VERSION}</p></div>`}
function lobby(){const g=state.game,me=g.players.find(p=>p.id===state.pid);return `<div class="shell"><div class="brand">LOBBY</div><h2>${esc(g.name)}</h2><div class="code">${state.code}</div><p style="text-align:center">Send this code to your friends. Everyone joins from their own PC.</p><div class="players">${g.players.map(p=>`<div class="player">${p.avatar} <b>${esc(p.name)}</b>${p.host?' 👑':''}<span class="status">${p.connected?(p.host?'Host':p.ready?'Ready':'Not ready'):'✕ Offline'}</span></div>`).join('')}</div><div class="row" style="margin-top:18px">${me.host?`<button ${g.players.length<2?'disabled':''} onclick="send({type:'START'})">${g.players.length<2?'Waiting for 2 players…':'Start Game 🚀'}</button>`:`<button onclick="send({type:'SET_READY',ready:${!me.ready}})">${me.ready?'✓ Ready — click to undo':'Ready up'}</button>`}<span class="notice">${g.players.length}/${g.settings.capacity} players • testing minimum 2</span></div></div>`}
function imageSubmit(){const mine=state.game.sources.filter(s=>s.ownerId===state.pid),need=state.game.settings.imagesPerPlayer,submitted=!!state.game.submittedSources?.[state.pid];return `<div class="shell"><div class="brand">ROUND SETUP</div><h2>📸 Build the image pool</h2><p>Submit <b>${need}</b> image${need===1?'':'s'}. Choose files, drag them in, or paste with Ctrl+V.</p><div id="drop" class="drop" tabindex="0" ondragover="event.preventDefault();this.classList.add('drag')" ondragleave="this.classList.remove('drag')" ondrop="handleDrop(event)"><strong>Drop images here</strong><br><button type="button" onclick="document.getElementById('file').click()">📁 Choose image files</button><div style="margin:10px 0;font-weight:900">or</div><span>📋 Copy an image and press <b>Ctrl+V</b></span><br><small>JPG, PNG, WebP and other browser-supported images.</small><input id="file" class="fileInput" type="file" accept="image/*" multiple></div><div class="thumbs">${mine.map(s=>`<div class="thumb"><img src="${s.data}"></div>`).join('')}</div><div class="row" style="margin-top:18px"><span class="notice">${mine.length}/${need} uploaded</span>${submitted?'<span class="notice">✓ Submitted — waiting for everyone</span>':mine.length>=need?'<button onclick="submitSources()">Continue →</button>':'<span>Keep adding images…</span>'}</div>${state.error?`<p class="error">${esc(state.error)}</p>`:''}</div>`}
function approval(){return `<div class="shell"><div class="brand">HOST CHECK</div><h2>🕵️ Approve the image pool</h2><div class="thumbs">${state.game.sources.map(s=>`<div class="thumb"><img src="${s.data}"><button onclick="send({type:'DELETE_SOURCE',sourceId:'${s.id}'})">Delete</button></div>`).join('')}</div>${state.game.players.find(p=>p.id===state.pid)?.host?`<button style="margin-top:18px" onclick="send({type:'APPROVAL_DONE'})">Looks good — continue →</button>`:'<p class="notice">Waiting for the host…</p>'}</div>`}
function prompts(){const count=state.game.prompts.length,total=state.game.players.length;return `<div class="shell"><div class="brand">PROMPT ROUND</div><h2>✍️ Give everyone something ridiculous to make</h2><textarea id="prompt" class="promptInput" style="min-height:130px" placeholder="Write a sentence, scenario or idea…">${esc(state.prompt)}</textarea><div class="row" style="margin-top:14px"><button onclick="submitPrompt()">Submit Prompt →</button><span class="notice">${count}/${total} submitted</span></div></div>`}
function round(){const g=state.game,prompt=g.prompts.find(p=>p.id===g.currentPromptId)?.text||'',remaining=Math.max(0,Math.ceil((g.timerEndsAt-Date.now())/1000));if(g.round>0&&!state.pieces.length){const owner=g.roundPlayerSets[state.pid],travel=g.travelingSets?.[owner];if(travel)state.pieces=scatter(travel)}return `<div class="shell wide"><div class="promptBanner"><div><small>ROUND ${g.round+1} OF ${g.players.length}</small><h2>${esc(prompt)}</h2></div><div class="timer">⏱ <span id="timerValue">${remaining}</span>s</div></div><div class="editorGrid"><aside><div class="sourcePanel">${g.round===0?`<h3>🖼 Your ingredients</h3><p>Select an image, then press <b>Cut</b>. Draw any shape around the bit you want.</p><div class="sourceList">${g.sources.map(s=>`<button class="sourceBtn ${state.sourceSelected===s.id?'active':''}" onclick="selectSource('${s.id}')"><img src="${state.sourceWorking[s.id]||s.data}"></button>`).join('')}</div>${state.sourceSelected?`<img class="sourcePreview" src="${state.sourceWorking[state.sourceSelected]||g.sources.find(s=>s.id===state.sourceSelected)?.data}">`:''}`:`<h3>🔀 Shuffled pieces</h3><p>These pieces came from another player's collage. Rearrange them.</p>`}</div><div class="toolPanel" style="margin-top:12px"><div class="toolbar">${g.round===0?`<button class="cutBtn" onclick="openCutTool()">✂ Cut freehand</button>`:''}<button onclick="rotate(-15)">↺</button><button onclick="rotate(15)">↻</button><button onclick="flip('x')">↔</button><button onclick="flip('y')">↕</button><button onclick="layer(-1)">↓</button><button onclick="layer(1)">↑</button></div><button style="width:100%;background:var(--green)" onclick="submitCollage()">Submit collage ✓</button></div></aside><div class="canvas" id="canvas">${state.pieces.map(p=>`<img class="piece ${state.selected===p.id?'selected':''}" draggable="false" src="${p.src}" style="left:${p.x}%;top:${p.y}%;width:${p.w||24}%;transform:translate(-50%,-50%) rotate(${p.rotation||0}deg) scaleX(${p.flipX?-1:1}) scaleY(${p.flipY?-1:1});z-index:${p.z||0}" onpointerdown="pieceDown(event,'${p.id}')">`).join('')}</div></div><p class="roundNote">${g.round===0?'Freehand cut any shape you like.':'No cutting this round — only rearrange what you inherited.'} • Pieces: ${state.pieces.length}</p></div>`}
function scatter(ps){return ps.map((p,i)=>({...JSON.parse(JSON.stringify(p)),id:uid(),x:15+((i*37)%70),y:15+((i*53)%70),z:i}));}
function voting(){const g=state.game,remaining=Math.max(0,Math.ceil((g.timerEndsAt-Date.now())/1000));return `<div class="shell wide"><div class="promptBanner"><div><small>VOTE</small><h2>${esc(g.prompts.find(p=>p.id===g.currentPromptId)?.text||'')}</h2></div><div class="timer">⏱ <span id="timerValue">${remaining}</span>s</div></div><p>Pick the collage that best answers the prompt. <b>No names are shown.</b></p><div class="voteGrid">${Object.values(g.collages).map(c=>`<div class="voteCard">${canvasHTML(c.pieces)}${c.playerId===state.pid?'<div class="notice" style="margin-top:8px">Your collage</div>':`<button style="width:100%;margin-top:8px" onclick="send({type:'VOTE',targetId:'${c.playerId}'})">Vote for this</button>`}</div>`).join('')}</div></div>`}
function canvasHTML(ps){return `<div class="miniCanvas">${ps.map(p=>`<img src="${p.src}" style="left:${p.x}%;top:${p.y}%;width:${p.w||24}%;transform:translate(-50%,-50%) rotate(${p.rotation||0}deg) scaleX(${p.flipX?-1:1}) scaleY(${p.flipY?-1:1})">`).join('')}</div>`}
function reveal(){const g=state.game;return `<div class="shell wide"><div class="brand">RESULTS</div><h2>🎉 Round ${g.round+1} results</h2><div class="voteGrid">${Object.values(g.collages).sort((a,b)=>(g.lastTally?.[b.playerId]||0)-(g.lastTally?.[a.playerId]||0)).map(c=>`<div class="voteCard">${canvasHTML(c.pieces)}<div class="result"><span>${g.lastTally?.[c.playerId]||0} votes</span></div></div>`).join('')}</div>${state.game.players.find(p=>p.id===state.pid)?.host?'<button style="margin-top:18px" onclick="send({type:\'NEXT\'})">Next round →</button>':'<p class="notice">Waiting for the host to continue…</p>'}</div>`}
function final(){const rows=[...state.game.players].sort((a,b)=>(state.game.scores[b.id]||0)-(state.game.scores[a.id]||0));return `<div class="shell"><div class="brand">FINAL SHOWCASE</div><h1>🏆</h1><h2>The Collage Hall of Shame</h2>${rows.map((p,i)=>`<div class="result"><b>${i+1}. ${esc(p.name)}</b><span>${state.game.scores[p.id]||0} pts</span></div>`).join('')}<p class="roundNote">Thanks for playing Shuffle. V${VERSION}</p></div>`}
function render(force=false){if(!force&&state.game?.phase===state.lastPhase)return;clearInterval(state.timerHandle);let html=state.screen==='home'?home():state.screen==='host'?host():state.screen==='join'?join():state.game?.phase==='LOBBY'?lobby():state.game?.phase==='IMAGE_SUBMISSION'?imageSubmit():state.game?.phase==='HOST_APPROVAL'?approval():state.game?.phase==='PROMPT_SUBMISSION'?prompts():state.game?.phase==='ROUND'?round():state.game?.phase==='VOTING'?voting():state.game?.phase==='REVEAL'?reveal():state.game?.phase==='FINAL'?final():`<div class="shell">Connecting…</div>`;app.innerHTML=html;state.lastPhase=state.game?.phase||null;bindPhase();startTimerIfNeeded();}
function bindPhase(){document.onpaste=state.game?.phase==='IMAGE_SUBMISSION'?onPaste:null;const file=document.querySelector('#file');if(file)file.addEventListener('change',e=>files(e.target.files));}
function startTimerIfNeeded(){if(!state.game?.timerEndsAt)return;const phase=state.game.phase;if(!['ROUND','VOTING'].includes(phase))return;state.timerHandle=setInterval(()=>{const el=document.querySelector('#timerValue');if(el)el.textContent=Math.max(0,Math.ceil((state.game.timerEndsAt-Date.now())/1000));},250);}
function updateLive(){if(state.game?.phase==='LOBBY'){const el=document.querySelector('.players');if(el){const g=state.game;el.innerHTML=g.players.map(p=>`<div class="player">${p.avatar} <b>${esc(p.name)}</b>${p.host?' 👑':''}<span class="status">${p.connected?(p.host?'Host':p.ready?'Ready':'Not ready'):'✕ Offline'}</span></div>`).join('')}}if(state.game?.phase==='IMAGE_SUBMISSION'){const count=state.game.sources.filter(s=>s.ownerId===state.pid).length;const notice=document.querySelector('.row .notice');if(notice)notice.textContent=`${count}/${state.game.settings.imagesPerPlayer} uploaded`;const drop=document.querySelector('.drop');if(drop&&!document.querySelector('.thumbs img')){/* no-op; thumbnails update on next explicit render */}}if(state.game?.phase==='ROUND')startTimerIfNeeded();if(state.game?.phase==='VOTING')startTimerIfNeeded();}
function go(s){state.screen=s;state.error='';state.game=null;state.lastPhase=null;render(true)}
function setName(v){state.name=v;localStorage.setItem('collageName',v)}function setAvatar(v){state.avatar=v;localStorage.setItem('collageAvatar',v);render(true)}
function startHost(){if(!state.name.trim()){state.error='Choose a nickname first.';render(true);return}connect(ws=>ws.send(JSON.stringify({type:'HOST_CREATE',name:state.name,avatar:state.avatar,lobbyName:state.lobby,settings:state.settings}))) }
function startJoin(){const n=document.querySelector('#joinName')?.value.trim()||state.name.trim(),c=document.querySelector('#joinCode')?.value.trim().toUpperCase()||state.code.trim().toUpperCase();state.name=n;state.code=c;localStorage.setItem('collageName',n);if(!n){state.error='Enter a nickname first.';render(true);return}if(c.length<4){state.error='Enter the 4-letter lobby code.';render(true);return}connect(ws=>ws.send(JSON.stringify({type:'JOIN',name:n,avatar:state.avatar,code:c}))) }
function files(list){const need=state.game?.settings.imagesPerPlayer||2,current=state.game?.sources?.filter(s=>s.ownerId===state.pid).length||0;const allowed=Math.max(0,need-current);[...list].filter(f=>f.type.startsWith('image/')).slice(0,allowed).forEach(file=>{const reader=new FileReader();reader.onload=()=>send({type:'ADD_SOURCE',data:reader.result});reader.readAsDataURL(file)});}
function onPaste(e){const item=[...(e.clipboardData?.items||[])].find(i=>i.type.startsWith('image/'));if(!item)return;e.preventDefault();const f=item.getAsFile();if(f)files([f]);}
function handleDrop(e){e.preventDefault();e.currentTarget.classList.remove('drag');files(e.dataTransfer.files)}
function submitSources(){send({type:'SUBMIT_SOURCES'})}
function submitPrompt(){const el=document.querySelector('#prompt');const t=el?.value.trim();if(t){state.prompt=t;send({type:'ADD_PROMPT',text:t})}}
function selectSource(id){state.sourceSelected=id;render(true)}
function openCutTool(){if(!state.sourceSelected){alert('Pick an image first.');return}const src=state.sourceWorking[state.sourceSelected]||state.game.sources.find(s=>s.id===state.sourceSelected)?.data;if(!src)return;const modal=document.createElement('div');modal.className='cutModal';modal.innerHTML=`<div class="cutBox"><h2>✂ Draw your cut</h2><div class="cutHint">Draw a closed shape around exactly what you want. It does not need to be a circle.</div><div class="cutCanvasWrap"><canvas class="cutCanvas"></canvas></div><div class="row" style="margin-top:12px"><button onclick="finishCut()">Cut this shape</button><button class="secondary" onclick="closeCut()">Cancel</button><span class="notice">Freehand • any shape</span></div></div>`;document.body.appendChild(modal);state.cutCanvas=modal.querySelector('canvas');state.cutPoints=[];const img=new Image();img.onload=()=>{const max=820,scale=Math.min(1,max/img.width,max/img.height);state.cutCanvas.width=Math.round(img.width*scale);state.cutCanvas.height=Math.round(img.height*scale);state.cutCanvas.dataset.source=src;const ctx=state.cutCanvas.getContext('2d');ctx.drawImage(img,0,0,state.cutCanvas.width,state.cutCanvas.height);setupLasso()};img.src=src}
function setupLasso(){const c=state.cutCanvas,ctx=c.getContext('2d');let drawing=false;c.onpointerdown=e=>{drawing=true;state.cutPoints=[[e.offsetX,e.offsetY]];ctx.beginPath();ctx.moveTo(e.offsetX,e.offsetY)};c.onpointermove=e=>{if(!drawing)return;state.cutPoints.push([e.offsetX,e.offsetY]);ctx.lineTo(e.offsetX,e.offsetY);ctx.strokeStyle='#ff4f87';ctx.lineWidth=4;ctx.stroke()};c.onpointerup=()=>{if(!drawing)return;drawing=false;if(state.cutPoints.length>2){const [x,y]=state.cutPoints[0];ctx.lineTo(x,y);ctx.stroke()}};c.onpointerleave=()=>{if(drawing)c.onpointerup()}}
function closeCut(){document.querySelector('.cutModal')?.remove();state.cutCanvas=null;state.cutPoints=[]}
function finishCut(){const c=state.cutCanvas;if(!c||state.cutPoints.length<8){alert('Draw a larger closed shape first.');return}const src=c.dataset.source,img=new Image();img.onload=()=>{const sx=img.width/c.width,sy=img.height/c.height,pts=state.cutPoints.map(([x,y])=>[x*sx,y*sy]),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minX=Math.max(0,Math.floor(Math.min(...xs))),minY=Math.max(0,Math.floor(Math.min(...ys))),maxX=Math.min(img.width,Math.ceil(Math.max(...xs))),maxY=Math.min(img.height,Math.ceil(Math.max(...ys)));const out=document.createElement('canvas');out.width=maxX-minX;out.height=maxY-minY;const o=out.getContext('2d');o.beginPath();pts.forEach(([x,y],i)=>i?o.lineTo(x-minX,y-minY):o.moveTo(x-minX,y-minY));o.closePath();o.clip();o.drawImage(img,-minX,-minY);const pieceSrc=out.toDataURL('image/png');const working=document.createElement('canvas');working.width=img.width;working.height=img.height;const w=working.getContext('2d');w.drawImage(img,0,0);w.globalCompositeOperation='destination-out';w.beginPath();pts.forEach(([x,y],i)=>i?w.lineTo(x,y):w.moveTo(x,y));w.closePath();w.fill();state.sourceWorking[state.sourceSelected]=working.toDataURL('image/png');const p={id:uid(),src:pieceSrc,x:50,y:50,w:Math.max(10,Math.min(60,(maxX-minX)/img.width*75)),rotation:0,flipX:false,flipY:false,z:state.pieces.length};state.pieces.push(p);state.selected=p.id;closeCut();render(true)};img.src=src}
function pieceDown(e,id){e.preventDefault();e.stopPropagation();const p=state.pieces.find(x=>x.id===id);if(!p)return;state.selected=id;const el=e.currentTarget,canvas=el.parentElement,r=canvas.getBoundingClientRect();state.drag={id,ox:e.clientX,oy:e.clientY,startX:p.x,startY:p.y,w:r.width,h:r.height};el.setPointerCapture?.(e.pointerId);el.onpointermove=ev=>{if(!state.drag)return;const dx=(ev.clientX-state.drag.ox)/state.drag.w*100,dy=(ev.clientY-state.drag.oy)/state.drag.h*100;p.x=Math.max(0,Math.min(100,state.drag.startX+dx));p.y=Math.max(0,Math.min(100,state.drag.startY+dy));el.style.left=p.x+'%';el.style.top=p.y+'%'};el.onpointerup=()=>{state.drag=null;el.onpointermove=null;el.onpointerup=null;render(true)}}
function rotate(d){const p=state.pieces.find(x=>x.id===state.selected);if(p){p.rotation=(p.rotation||0)+d;render(true)}}function flip(axis){const p=state.pieces.find(x=>x.id===state.selected);if(p){const k=axis==='x'?'flipX':'flipY';p[k]=!p[k];render(true)}}function layer(d){const p=state.pieces.find(x=>x.id===state.selected);if(p){p.z=Math.max(0,(p.z||0)+d);render(true)}}function submitCollage(){send({type:'SUBMIT_COLLAGE',pieces:state.pieces})}
window.go=go;window.setName=setName;window.setAvatar=setAvatar;window.startHost=startHost;window.startJoin=startJoin;window.files=files;window.handleDrop=handleDrop;window.submitSources=submitSources;window.submitPrompt=submitPrompt;window.selectSource=selectSource;window.openCutTool=openCutTool;window.closeCut=closeCut;window.finishCut=finishCut;window.pieceDown=pieceDown;window.rotate=rotate;window.flip=flip;window.layer=layer;window.submitCollage=submitCollage;
render(true);
